version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: nginx_web_server
    ports:
      - "8080:80"
    volumes:
      # Mappt nur deinen Frontend-Ordner auf den Standard-Nginx-Pfad
      - ../Frontend:/usr/share/nginx/html:ro
    environment:
      - TZ=UTC
    restart: always

  backend:
    build: 
      context: ../java
      dockerfile: Dockerfile
    container_name: java_backend
    ports:
      - "8081:8080"
    # Das Volume für die Datenbank wurde entfernt, 
    # da die fakedb.md beim Bauen automatisch in die .jar gepackt wird.
    restart: always